version: 2
jobs:
  docker-swift-updater:
    docker:
      - image: norionomura/docker-swift-updater
    steps:
      - checkout
      - add-ssh-keys:
          fingerprints:
            - "fe:11:f3:6a:1e:7c:38:67:33:d2:ff:42:1a:16:01:87"
      - setup_remote_docker
      - run: |
            git config --global user.name "Norio Nomura"
            git config --global user.email "norio.nomura@gmail.com"
            git fetch --tags
      - run: docker-swift-updater -Verbose YES
      - run: |
            git push origin $CIRCLE_BRANCH
            git push --tags origin $CIRCLE_BRANCH

workflows:
  version: 2
  hourly:
    triggers:
      - schedule:
          cron: "25 * * * *"
          filters:
            branches:
              only:
                - nightly
    jobs:
      - docker-swift-updater
