#!/bin/bash

# https://docs.docker.com/docker-cloud/builds/advanced/

function add_tag() {
  docker tag $IMAGE_NAME $DOCKER_REPO:$1
  docker push $DOCKER_REPO:$1
}

IFS="-" read -r -a TAG<<<"${SOURCE_BRANCH}"
test ${#TAG[@]} -eq  3 || exit 1
test "${TAG[0]}" == "pr" || exit 1

add_tag pr-${TAG[1]}

exit $?
